version: "3.9"


networks:
  infosec-network:
    name: infosec-network


services:
  infosec-api:
    container_name: infosec-api
    build:
      context: .
    image: infosec-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_EXPOSED_PORT:-8000}:8000"
    networks:
      - infosec-network
    volumes:
      - ./app:/app/app

  infosec-postgres:
    container_name: infosec-postgres
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "${POSTGRES_EXPOSED_PORT:-5432}:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - infosec-network