version: "3.9"

networks:
  infosec-network:
    name: infosec-network
    driver: bridge

volumes:
  infosec-postgres-volume:
    name: infosec-postgres-volume

services:
  infosec-api:
    container_name: infosec-api
    build:
      context: .
    image: infosec-api
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - infosec-network
    volumes:
      - ./app:/app/app

  infosec-postgres:
    container_name: infosec-postgres
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - infosec-postgres-volume:/var/lib/postgresql/data
    networks:
      - infosec-network

  infosec-nginx:
    image: nginx:latest
    container_name: infosec-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf/:/etc/nginx/conf.d
    depends_on:
      - infosec-api
    networks:
      - infosec-network
